# Generated by Django 4.2.14 on 2025-01-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
